import = ["/Users/rope/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "alacritty-direct"

[font]
size = 15

[font.normal]
# family = "UbuntuMono Nerd Font"
family = "Monaco Nerd Font"

[[keyboard.bindings]]
chars = "e ~/dotfiles/alacritty/.config/alacritty/alacritty.toml\r"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command"

[mouse]
hide_when_typing = true

[window]
decorations = "buttonless"
opacity = 1
option_as_alt = "OnlyRight"

[window.padding]
x = 2
y = 2
